timeout: 60000
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/crossover
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  logging:
    level:
      net:
        artcoder:
          DEBUG
      org:
        springframework:
          web: INFO

  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update

